one:
	./test.sh one "Task-1.py" "\['8', '7', '6', '6', '7', '8'\]"

two:
	./test.sh two "Task-2.py" "\['hop', 'hoop'\]"

three:
	./test.sh three "Task-3.py" "\['cloudacademy.com'\]"

four:
	./test.sh four "Task-4.py" "\['space1', '2apple', 'brush3'\]"

five:
	./test.sh five "Task-5.py" "\['1.1.1.1', '2.2.2.2', '3.3.3.3', '4.4.4.4'\]"
