one:
	mkdir -p ../check && [cp ../src/*.py ../check
	python3 ../check/Task-1.py | grep "['8', '7', '6', '6', '7', '8']"

two:
	mkdir -p ../check && cp ../src/*.py ../check
	python3 ../check/Task-2.py | grep "['hop', 'hoop']"

three:
	mkdir -p ../check && cp ../src/*.py ../check
	python3 ../check/Task-3.py | grep "['cloudacademy.com']"

four:
	mkdir -p ../check && cp ../src/*.py ../check
	python3 ../check/Task-4.py | grep "['space1', '2apple', 'brush3']"

five:
	mkdir -p ../check && cp ../src/*.py ../check
	python3 ../check/Task-5.py | grep "['1.1.1.1', '2.2.2.2', '3.3.3.3', '4.4.4.4']" output.txt
